const {readFileSync} = require('node:fs');
const vm=require('node:vm'), assert=require('node:assert/strict');
const html=readFileSync('index.html','utf8');
const code=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/\binit\(\);\s*$/,'');
const nodes=new Map();
const document={getElementById(id){if(!nodes.has(id))nodes.set(id,{textContent:'',innerHTML:'',value:'',classList:{toggle(){}}});return nodes.get(id);}};
const store=new Map();
const context=vm.createContext({document,URL,URLSearchParams,console,setTimeout,clearTimeout,localStorage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)},location:{hostname:'example.org',search:''},prompt:()=>{throw Error('No unsolicited login');}});
vm.runInContext(code,context);
const run=expression=>vm.runInContext(expression,context);
const plain=expression=>JSON.parse(JSON.stringify(run(expression)));
assert.deepEqual(plain("clubKeysFromRaw('0174246 - SEYNOD, 0335067 - RENNES')"),['0174246','0335067']);
run("state.clubCatalog=[{label:'0174246 - SEYNOD'},{label:'0335067 - RENNES'}]");
assert.deepEqual(plain("clubKeysFromRaw('Seynod')"),['0174246']);
assert.deepEqual(plain("clubKeysFromRaw('Seynod, 0335067 - RENNES')"),['0174246','0335067']);
assert.equal(run("addClubToRaw('0174246','0335067 - RENNES')"),'0174246, 0335067');
run("state.selectionMode='archers';state.selectedArchers=[{name:'DUPONT Paul',club:'0335067 - RENNES',clubCode:'0335067'}]");
assert.equal(run("matchesScope({name:'DUPONT Paul',club:'0335067 - RENNES'},['0174246'])"),true);
assert.equal(run("matchesScope({name:'DUPONT Paul',club:'0174246 - SEYNOD'},['0174246'])"),false);
assert.equal(run("matchesScope({name:'DUPONT Pauline',club:'0335067 - RENNES'},['0174246'])"),false);
assert.equal(run("isFinished({progress:'Après 60 flèches',category:'TAE 70m'})"),false);
assert.equal(run("isFinished({progress:'Après 60 flèches',category:'Salle 18m'})"),true);
assert.equal(run("isFinished({progress:'Après 48 flèches',detail:'70m-1: 280, 70m-2: 90'})"),false);
assert.equal(run("getScore({score:0,scoreLabel:'après 36 flèches'})"),0);
run("state.catalogTournaments=[{name:'Today',entries:[{name:'MARTIN Élodie',club:'0335067 - RENNES'}]}]");
assert.equal(run("catalogArcherSearch('elodie martin').length"),1);
run("state.volley={};state.selectedCompetition='all'");
run("syncVolley({competitions:[{id:'1',name:'T',archers:[{name:'Paul',club:'0335067',category:'Salle',score:200,arrows:24}]}]})");
run("syncVolley({competitions:[{id:'1',name:'T',archers:[{name:'Paul',club:'0335067',category:'Salle',score:220,arrows:30}]}]})");
assert.equal(run("Object.values(state.volley)[0].history.at(-1).type"),'grouped');
run("syncVolley({competitions:[{id:'1',name:'T',archers:[{name:'Paul',club:'0335067',category:'Salle',score:245,arrows:33}]}]})");
assert.equal(run("Object.values(state.volley)[0].history.at(-1).type"),'volley');
assert(!html.includes('ADMIN_HASH'));assert(!html.includes('slc_admin_ok'));assert(!html.includes('loadPdfResults'));
(async()=>{assert.equal(await run('resolveAdmin()'),false);run("location.search='?admin=seynod-admin'");assert.equal(await run('resolveAdmin()'),false);console.log('Frontend regression checks passed');})().catch(e=>{console.error(e);process.exit(1);});
